### PR TITLE
refactor: upgrade for node20

### PR DESCRIPTION
**Pull request by alexkainzinger**
Hi, contributing to make this run with node20 due to https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

code is not touched at all, just removing `node_modules/` folder because it is now compiled instead with ncc and put to `dist/` folder. this also bumps all packages to its newest version, rest is just search and replace node16 with node20

I tested it in my private repo using my published v2: `alexkainzinger/compose-action@v2` (https://github.com/alexkainzinger/compose-action/tree/v2) and it worked like a charm

### CODE REVIEW

**Review by rchabin — APPROVED** [review]

**Comment by longmauriceproj** [comment]
Do we have an update on when this PR will be merged?

**Comment by alexkainzinger** [comment]
I guess until merged I can only recommend using my fork `alexkainzinger/compose-action@v2`

**Comment by alexkainzinger** [comment]
@neilime I guess I cannot contribute to this anymore, pipeline fails with something I cannot fix I would assume

**Comment by neilime** [comment]
We are working to refactoring to typescript and migrating to node 20, new release will be available very soon

**Comment by neilime** [comment]
@alexkainzinger the migration on node 20 is done, thank you for you PR for inspiration. I'll close it.

**Pull request closed without merging**
